CREATE TABLE IF NOT EXISTS chats (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    senderId INTEGER NOT NULL,
    receiverId INTEGER NOT NULL,
    content TEXT NOT NULL,
    statusReceived BOOLEAN NOT NULL DEFAULT FALSE,
    statusRead BOOLEAN NOT NULL DEFAULT FALSE,
    createdAt DATETIME NOT NULL
);